spring:
  application:
    name: am-schedule
  data:
    mongodb:
      authentication-database: admin
      password: pass123
      username: mongofiboadmin
      host: localhost
      port: 27017
      database: schedule