spring:
  application:
    name: am-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 'password'
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/schedule'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

ru:
  am:
    scheduleapp:
      use-date-filter: false
      wb-dir-location: '/tmp/wb/'


rsa:
  private-key: 'classpath:certs/private_key.pem'
  public-key: 'classpath:certs/public_key.pem'

server:
  port: 8087
  ssl:
    key-store: 'classpath:keystore/keystore.p12'
    key-store-password: cb92b467-1d2a-403d-9a4f-c34e1575eb83
    keyStoreType: PKCS12
    keyAlias: am
    enabled: false
