spring:
  application:
    name: am-schedule
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 'password'
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/crm'
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    generate-ddl: true

ru:
  am:
    scheduleapp:
      use-date-filter: false
      wb-dir-location: '/tmp/wb/'
      google-creds-file-path: '/etc/am/google/creds-service.json' # '/etc/am/google/creds.json'

server:
  port: 8087
